Add README.md to remote_settings
mozilla/firefox-translations-models pull request #134
Opened 2024-01-29 18:00 UTC by nordzilla

2024-01-29 18:37 UTC, eu9ene requested changes
Let's add a specific example on how to upload a newly added model.

2024-01-29 18:37 UTC, eu9ene commented on remote_settings/README.md
> +### Examples
Ok, I was able to follow the instructions and upload the models.

What I think would be great to add here:

1. What are exact steps a users needs to do after a model was added to a repo? We should clarify that 3 model files should be uploaded, ideally just provide an example of this.
2. The model files in the directory should be unzipped first
3. What happens after we run the command 3 times for each of the files? How the review process works? Will it be just one review or 3 reviews?

I would add a code example of uploading the full model directory:

```
gzip -d  models/dev/elen/*.gz
export REMOTE_SETTINGS_BEARER_TOKEN="Bearer ..."

poetry run python -m remote_settings create --path models/dev/elen/lex.50.50.elen.s2t.bin --server prod  --version 1.0a1
poetry run python -m remote_settings create --path models/dev/elen/vocab.elen.spm --server prod  --version 1.0a1
poetry run python -m remote_settings create --path models/dev/elen/model.elen.intgemm.alphas.bin --server prod  --version 1.0a1
```

2024-01-29 18:37 UTC, eu9ene commented on remote_settings/README.md
> +### Examples
We would also benefit from automation here. For example it's crucial to use the same version and server for a language pair, so we could write a bash script that does all that for us. We would provide just a directory and a version (in fact per current structure it should determine the version based on the directory name dev/prod).

It would look like this:

```
bash scripts/release.sh dev elen
```

I can add it.

2024-01-29 18:54 UTC, nordzilla commented on remote_settings/README.md
> +### Examples
> Ok, I was able to follow the instructions and upload a model.
> 
> What I think would be great to add here:
> 
>     1. What are exact steps a users needs to do after a model was added to a repo? We should clarify that 3 model files should be uploaded, ideally just provide an example of this.
> 
>     2. The model files in the directory should be unzipped first
> 
>     3. What happens after we run the command 3 times for each of the files? How the review process works? Will it be just one review or 3 reviews?
> 
> 
> I would add a code example of uploading the full model directory:
> 
> ```
> gzip -d  models/dev/elen/*.gz
> export REMOTE_SETTINGS_BEARER_TOKEN="Bearer ..."
> 
> poetry run python -m remote_settings create --path models/dev/elen/lex.50.50.elen.s2t.bin --server prod  --version 1.0a1
> poetry run python -m remote_settings create --path models/dev/elen/vocab.elen.spm --server prod  --version 1.0a1
> poetry run python -m remote_settings create --path models/dev/elen/model.elen.intgemm.alphas.bin --server prod  --version 1.0a1
> ```

Thanks for the feedback. I'll add these before the end of the day. 

> We would also benefit from automation here. For example it's crucial to use the same version and server for a language pair, so we could write a bash script that does all that for us. We would provide just a directory and a version (in fact per current structure it should determine the version based on the directory name dev/prod).
> 
> It would look like this:
> 
> ```
> bash scripts/release.sh dev elen
> ```
> 
> I can add it.

This was on my to-do list for Q1, but in this PR I was just trying to document the CLI tool itself. 

If you want to add a wrapper script for this, you're more than welcome to.

2024-01-29 19:10 UTC, evgenyrp commented on remote_settings/README.md
> +### Examples
I added a simple script that helps releasing a model here https://github.com/mozilla/firefox-translations-models/pull/135. So you can just refer to it.

2024-01-30 03:39 UTC, nordzilla commented
I've updated the script to include a `--lang-pair` argument, which is a mutually exclusive alternative to `--path`. 

This argument uploads each model for the given language pair. 

The directory is determined by the version, e.g. `--lang-pair esen --version 1.0` would look in `models/prod/esen`. If the version were `1.0a1` it would look in `models/dev/esen`.

2024-01-30 19:20 UTC, eu9ene commented on tests/remote_settings/attachments/dev/enes/lex.50.50.enes.s2t.bin
Can we gzip those files? They might be quite heavy.

2024-01-30 19:20 UTC, eu9ene commented on remote_settings/README.md
> +* Run the script for the files you wish to upload.
I would still add specific instructions of what to do after adding a new model in the very beginning. As a user I don't care much how the cli works but just what I need to do to release the models from dev or prod folder.

I would want to follow this without further reading about advanced usage of the tool (for example I likely will never need to upload the files one by one using --path if I can upload the whole language pair):

`export REMOTE_SETTINGS_BEARER_TOKEN="Bearer ..."` (see Authentication).

To release a prod model to all Firefox channels:
```
gzip -d models/prod/deen/*
poetry run python -m remote_settings create --lang-pair deen --server prod --version 1.0
```

To release a dev model to Nightly only:
```
gzip -d models/dev/elen/*
poetry run python -m remote_settings create --lang-pair elen --server prod --version 1.0a1
```
Bump the version if uploading the updated model (see versioning).

2024-01-30 19:20 UTC, eu9ene commented on remote_settings/README.md
> +* Alpha-version records, e.g. `--version 1.0a1` will be available only in local builds and nightly builds.
It's still not clear to me what to do about version. Am I supposed to bump the version myself when uploading the updated model? Or can I just override with the same 1.0 and it will work? I suggest documenting it somewhere in the very top, before all the details of how the tool works.

2024-02-01 15:28 UTC, nordzilla commented on remote_settings/README.md
> +* Run the script for the files you wish to upload.
I've added a top-level example with step-by-step on how to publish.

2024-02-01 15:29 UTC, nordzilla commented on remote_settings/README.md
> +* Alpha-version records, e.g. `--version 1.0a1` will be available only in local builds and nightly builds.
I've added a top-level example with step-by-step on how to publish. 

It includes a note callout section about versioning.

2024-02-01 15:29 UTC, nordzilla commented on tests/remote_settings/attachments/dev/enes/lex.50.50.enes.s2t.bin
All of these files are empty.

They just exist in the testing directory for the tests to ensure that the correct metadata is derived by our naming conventions.

2024-02-01 15:30 UTC, nordzilla commented
I've updated the README to include a top-level example for publishing a model.

It includes a note callout section about the fact that versioning is entered manually at this time.

The updated README can still be previewed here:
https://github.com/mozilla/firefox-translations-models/tree/remote-settings-readme/remote_settings

2024-02-01 22:55 UTC, eu9ene approved these changes
Thank you for clarifying things! It's easier to follow the readme now. Looks good but something went wrong with CI. Ideally `evaluation` step shouldn't run at all if only `remote_settings` folder was modified

2024-02-02 17:31 UTC, merged